import {MINERAL_IDS} from './mineral-homes.mjs';
import {FINAL_DESIGNS,finalAsset,collectionAsset,FINAL_ROOM_NOTES} from './final-assets.mjs';
import {COLLECTIONS,LIFE_ROOM_NAMES} from './lifestyle-data.mjs';
import {HOMES,homeAsset} from './home-designs.mjs';
import {loadMediaImage,resolvedMediaURL,setMediaImage} from './media-loader.mjs';
import {openImageDialog} from './dialog-view.mjs';
export const designerRooms=Object.keys(LIFE_ROOM_NAMES);
export const v34Asset=path=>(globalThis.__TINGJIAN_V34_ORIGIN__||'')+path;
export const designerAsset=collectionAsset;
export function designerFrames(collection,design){const asset=(room,thumb=false)=>collection==='base'?homeAsset(design,room,thumb):collection==='final'?finalAsset(design,room,thumb):collectionAsset(collection,room,thumb);return designerRooms.map(id=>({id,name:LIFE_ROOM_NAMES[id],path:asset(id),thumb:asset(id,true)}));}
export function initDesignerGallery(root){
 const $=s=>root.querySelector(s);let design=null,collection='final',room='living',lastInput=null,job=0,exporting=false;
 const make=(tag,text)=>{const el=document.createElement(tag);if(text)el.textContent=text;return el;};
 const btn=(text,key,value,fn,active)=>{const b=make('button',text);b.type='button';b.dataset[key]=value;b.setAttribute('aria-pressed',String(active));b.addEventListener('click',fn);return b;};
 const title=()=>collection==='base'?HOMES[design].name+' · 原方案':collection==='final'?HOMES[design].name+' · 完整搭配':COLLECTIONS.find(c=>c.id===collection).name;
 async function load(){const id=++job,f=designerFrames(collection,design).find(f=>f.id===room),label=title()+' · '+f.name;const image=$('[data-designer-image]');image.hidden=true;$('[data-designer-loading]').hidden=false;$('[data-designer-loading]').textContent='正在载入'+f.name+'…';$('[data-designer-error]').hidden=true;$('[data-designer-large]').disabled=true;$('[data-designer-save]').hidden=true;
  $('[data-designer-room-title]').textContent=label;$('[data-designer-room-note]').textContent=collection==='base'?'原方案留存对照；修正后的布置请查看最终效果或延伸搭配。':FINAL_ROOM_NOTES[room];
  try{const im=await loadMediaImage(f.path);if(id!==job)return;image.src=im.loadedURL||resolvedMediaURL(f.path);image.alt=label;image.hidden=false;$('[data-designer-large]').disabled=false;$('[data-designer-save]').href=image.src;$('[data-designer-save]').download=label+'.webp';$('[data-designer-save]').hidden=false;}
  catch(e){if(id===job){$('[data-designer-error]').hidden=false;$('[data-designer-error-copy]').textContent='这张图暂未载入，可以重试或切换其他房间。';}}
  finally{if(id===job)$('[data-designer-loading]').hidden=true;}
 }
 function render(nextDesign,nextCollection){if(!nextDesign)return;if(design!==nextDesign){design=nextDesign;collection=FINAL_DESIGNS.includes(design)?'final':'base';room='living';}lastInput=nextCollection;const tabs=$('[data-designer-collections]');tabs.replaceChildren();for(const c of [...(FINAL_DESIGNS.includes(design)?[{id:'final',name:HOMES[design].name+' · 最终效果'}]:[]),...(MINERAL_IDS.includes(design)?[]:[{id:'base',name:'原方案对照'}]),...COLLECTIONS])tabs.append(btn(c.name,'designerCollection',c.id,()=>{collection=c.id;room='living';render(design,lastInput);},collection===c.id));
  $('[data-designer-title]').textContent=title()+' · 八个空间';const rooms=$('[data-designer-rooms]');rooms.replaceChildren();for(const f of designerFrames(collection,design)){const b=btn('','designerRoom',f.id,()=>{room=f.id;render(design,lastInput);},room===f.id),im=make('img');setMediaImage(im,f.thumb);im.alt='';im.width=240;im.height=160;im.loading='lazy';b.append(im,make('span',f.name));rooms.append(b);}load();
 }
 $('[data-designer-retry]').addEventListener('click',load);
 for(const [key,delta] of [['prev',-1],['next',1]])$('[data-designer-'+key+']').addEventListener('click',()=>{room=designerRooms[(designerRooms.indexOf(room)+delta+designerRooms.length)%designerRooms.length];render(design,lastInput);});
 const dialog=$('[data-designer-dialog]');$('[data-designer-large]').addEventListener('click',()=>{const im=$('[data-designer-image]');if(im.hidden)return;$('[data-designer-dialog-image]').src=im.src;$('[data-designer-dialog-image]').alt=im.alt;$('[data-designer-dialog-title]').textContent=im.alt;openImageDialog(dialog,window,{fullscreen:true});});$('[data-designer-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 $('[data-designer-export]').addEventListener('click',async()=>{if(exporting)return;exporting=true;const list=designerFrames(collection,design),name=title(),description=collection==='base'?'原方案留存图，仅供对照，不代表本轮修正后的布置。':'按原两房双阳台关系设计的八空间概念图。次卧约7.2㎡，景观阳台采用落地玻璃。预设完整搭配，不随单品选择实时重绘；尺寸仍需现场复核。',b=$('[data-designer-export]'),status=$('[data-designer-export-status]');b.disabled=true;status.textContent='正在打包八张原尺寸设计图…';try{const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cards='';for(const f of list){await loadMediaImage(f.path);const response=await fetch(resolvedMediaURL(f.path),{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error();const blob=await response.blob(),data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});cards+='<article><h2>'+escape(f.name)+'</h2><img src="'+data+'" alt="'+escape(f.name)+'"></article>';}
 const html='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(name)+'</title><style>body{max-width:1200px;margin:auto;padding:28px;background:#eee9e0;color:#40352c;font:16px/1.8 system-ui}img{width:100%;height:auto}article{break-inside:avoid;margin:35px 0}@media print{article{page-break-after:always}}</style><h1>'+escape(name)+' · 全屋设计图册</h1><p>'+escape(description)+'</p>'+cards;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=make('a');a.href=url;a.download='庭间-'+name+'-设计图册.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='八个空间已打包下载。';}catch{status.textContent='有图片未载入，未生成不完整图册，请重试。';}finally{exporting=false;b.disabled=false;}});
 return {render,resetSelection:()=>{design=null;},cancel:()=>{job++;},getState:()=>({collection,room,design})};
}
