import {collectionAsset} from './final-assets.mjs';
// Styling intentions and local scene simulation. No device connection or product endorsement.
export const COLLECTIONS=[
 {id:'collector',name:'木影藏家',subtitle:'胡桃木 · 古铜 · 烟褐织物',get image(){return collectionAsset('collector','living');},colors:['#39291f','#8b6b43','#7e6b5c'],text:'用一盏有年代感的灯、一件雕塑和留白的画面建立重心。屏幕收进画框，开关与古铜五金统一。',accent:'#806744'},
 {id:'oriental',name:'东方新序',subtitle:'红棕木 · 青瓷 · 暖橘余韵',get image(){return collectionAsset('oriental','living');},colors:['#4e3025','#7f8b79','#b87535'],text:'借器物与疏密表达东方气质：一枝、一器、一处茶席。窗帘轨道与光源藏起来，让窗景继续做主角。',accent:'#75806b'},
 {id:'nocturne',name:'紫夜艺廊',subtitle:'近黑茄紫 · 深棕 · 烟金',get image(){return collectionAsset('nocturne','living');},colors:['#251e2b','#48352b','#8d795e'],text:'深紫延伸到织物、艺术背景和小体量陈设，配深棕与半透石灯。亮度留给局部光与材质反光。',accent:'#352638'}
];
const dry=['living','dining','master','second','balcony'];
export const LIFE_CATEGORIES=[{id:'all',name:'全部搭配'},{id:'textile',name:'织物与窗饰'},{id:'art',name:'艺术与器物'},{id:'light',name:'灯具与光'},{id:'smart',name:'隐形智能'},{id:'appliance',name:'生活电器'}];
export const LIFE_ITEMS=[
 {id:'textile',category:'textile',name:'层次织物',rooms:['living','master','second','balcony'],model:true,copy:'用有纹理的靠垫与搭毯串联墙面、木色，控制在同一深浅关系里。',variants:['烟褐羊毛 × 鞍棕细边','深茶亚麻 × 苔色滚边','墨紫粗织 × 巧克力棕'],position:'沙发一侧或床尾；保留原有大件',prepare:'后期软装 · 先带布样核对日光与灯光下的颜色'},
 {id:'curtain',category:'textile',name:'双层电动窗帘',rooms:['living','master','second','balcony'],model:true,copy:'轻纱调节眩光，厚帘承担遮光；侧收时尽量把完整窗景露出来。',variants:['烟褐厚帘与灰米纱','茶褐亚麻与暖灰纱','深梅褐厚帘与烟灰纱'],position:'窗边侧收，轨道藏入帘盒',prepare:'硬装预留 · 帘盒尺寸、电源、检修口与双轨间距',source:'https://www.lutron.com/us/en/articles/how-to-layer-window-treatments-with-motorized-shades'},
 {id:'sculpture',category:'art',name:'案头器物',rooms:dry,model:true,copy:'每个角落只放一个视觉中心，用轮廓、触感和空隙代替堆满装饰。',variants:['古铜抽象雕塑与深石底座','青瓷长颈器与疏枝','近黑陶器与烟金圆环'],position:'边几、玄关柜或阳台茶席',prepare:'后期软装 · 校核底座稳定与通行净宽'},
 {id:'artwork',category:'art',name:'收藏级留白挂画',rooms:['living','dining','master','second'],model:true,copy:'一幅有留白的大画，比满墙小画更安静；框色呼应木作或金属。',variants:['古铜细框与深褐抽象画','深木框与当代水墨','烟金框与暗紫肌理画'],position:'玄关或空白墙；客厅与艺术电视二选一',prepare:'后期软装 · 先确定画心比例、挂点与灯位'},
 {id:'lamp',category:'light',name:'雕塑感氛围灯',rooms:dry,model:true,copy:'让灯具既是光源也是一件器物，光落在手边和材质上。',variants:['古铜蘑菇灯','深铜纸感灯罩','雪花石球灯与深铜灯座'],position:'沙发侧、床边或阅读角',prepare:'硬装预留 · 就近插座；调光灯与驱动需匹配'},
 {id:'lighting',category:'light',name:'分层调光系统',rooms:['living','dining','master','second','kitchen','bath','balcony','utility'],model:true,copy:'基础光、阅读光与低位引导光分回路。回家、阅读、夜起使用不同亮度。',position:'洗墙与柜下藏光，保留实体按键',prepare:'硬装预留 · 调光回路、驱动检修与零线；不靠彩色灯带营造科技感',source:'https://www.lutron.com/us/en/articles/types-lighting-controls-their-benefits'},
 {id:'presence',category:'smart',name:'分区存在感应',rooms:['living','dining','master','second','bath','utility'],model:true,copy:'按阅读区、通道等分区触发灯光；静坐阅读也能保持照明。',position:'墙角或顶面，避开窗帘与风扇干扰',prepare:'安装调试 · 现场标定范围与延迟；是否支持本地联动取决于具体设备',source:'https://www.aqara.com/us/product/presence-sensor-fp2'},
 {id:'climate',category:'smart',name:'空气与舒适联动',rooms:['living','master','second','kitchen','bath'],model:false,copy:'把空气监测、新风或排风列为同一场景，减少多个遥控器的存在感。',position:'监测点避开送风口与直接日晒',prepare:'机电深化 · 新风、温控接口和传感器需逐项核对兼容性'},
 {id:'panel',category:'smart',name:'材质一致的场景面板',rooms:['living','dining','master','second'],model:true,copy:'用触感好的实体按键承接回家、观影与离家；手机只是辅助。',position:'门边顺手处，与插座统一高度和饰面',prepare:'硬装预留 · 底盒深度、零线、联网条件与手动控制'},
 {id:'art-tv',category:'smart',name:'画框式艺术电视',rooms:['living'],model:true,copy:'不用时展示画作或照片，开机才成为屏幕，减少一块黑屏打断木作。',position:'客厅电视墙；替换本步骤的挂画选项',prepare:'硬装预留 · 电源、走线与散热；艺术内容授权和订阅需单独确认',source:'https://www.samsung.com/us/lifestyle-tvs/the-frame/'},
 {id:'audio',category:'smart',name:'低存在感背景音响',rooms:['living','master','balcony'],model:true,copy:'以低音量覆盖阅读与会客区，面网或小体量音箱融入柜体。',position:'靠墙或柜边；不封死声学开口',prepare:'硬装预留 · 线缆与安装腔体；独立关音按键'},
 {id:'mirror',category:'appliance',name:'柔光防雾镜',rooms:['bath'],model:true,copy:'梳洗时补脸部柔光，防雾按需开启；不把信息屏塞满镜面。',position:'洗手台镜区',prepare:'机电深化 · 湿区安装位置、防护等级与电源由专业人员确认'},
 {id:'coffee',category:'appliance',name:'隐藏式咖啡角',rooms:['kitchen','dining'],model:true,copy:'设备集中在可关闭的深木壁龛，打开是生活仪式，合上仍是一面完整柜体。',position:'厨房台面或餐边柜内',prepare:'柜体深化 · 校核电源、散热、蒸汽与清洁空间'},
 {id:'laundry',category:'appliance',name:'家政设备一体收纳',rooms:['utility'],model:true,copy:'烘干、清洁工具与耗材集中收纳，检修和日常取用保持顺手。',position:'生活阳台家政柜',prepare:'机电深化 · 上下水、排水防臭、通风与检修；按型号确定叠放条件'},
 {id:'cleaning',category:'appliance',name:'清洁机器人归位舱',rooms:['utility','dining'],model:true,copy:'把基站藏进柜下，同时留出机器人回航和人工清洁的位置。',position:'柜体底部，不占主要通道',prepare:'柜体深化 · 基站净空、回航距离与上下水视机型确定'}
];
export const LIFE_SCENES=[{id:'home',name:'归家',light:65,curtain:70,description:'玄关与活动区先亮起来，帘与背景声按自己的习惯开启。'},{id:'reading',name:'阅读',light:85,curtain:55,description:'手边阅读光优先，窗帘柔化眩光，空间保持安静。'},{id:'cinema',name:'观影',light:15,curtain:0,description:'关闭遮光帘，保留少量通行光，艺术屏切换观影。'},{id:'night',name:'夜起',light:8,curtain:0,description:'只保留低位引导光，避免整屋突然亮起。'},{id:'away',name:'离家',light:0,curtain:30,description:'关闭非必要照明和背景音；冰箱、网络与必要设备保持供电。'}];
export const LIFE_ROOM_NAMES={living:'客厅',dining:'餐厅 / 玄关',master:'主卧',second:'次卧 / 书房',kitchen:'厨房',bath:'卫生间',balcony:'景观阳台',utility:'生活阳台'};
export const suggestedCollection=design=>['mauve-walnut','plum-gallery'].includes(design)?'nocturne':['chinese','orange-court','milan','stone'].includes(design)?'oriental':'collector';
export function emptyLifestyle(design){return {collection:suggestedCollection(design),rooms:Object.fromEntries(Object.keys(LIFE_ROOM_NAMES).map(r=>[r,[]])),scene:'home'};}
export function normalizeLifestyle(value,design){const next=emptyLifestyle(design);if(!value)return next;if(COLLECTIONS.some(c=>c.id===value.collection))next.collection=value.collection;if(LIFE_SCENES.some(s=>s.id===value.scene))next.scene=value.scene;for(const r of Object.keys(next.rooms)){next.rooms[r]=[...new Set((value.rooms?.[r]||[]).filter(id=>LIFE_ITEMS.some(i=>i.id===id&&i.rooms.includes(r))))];if(next.rooms[r].includes('art-tv'))next.rooms[r]=next.rooms[r].filter(id=>id!=='artwork');}return next;}
export function toggleLifestyleItem(value,room,id){const next=normalizeLifestyle(value),item=LIFE_ITEMS.find(i=>i.id===id);if(!item?.rooms.includes(room))return next;const picked=next.rooms[room];if(picked.includes(id))next.rooms[room]=picked.filter(x=>x!==id);else{if(id==='art-tv')next.rooms[room]=picked.filter(x=>x!=='artwork');if(id==='artwork')next.rooms[room]=picked.filter(x=>x!=='art-tv');next.rooms[room].push(id);}return next;}
export function recommendLifestyle(value){const next=normalizeLifestyle(value);for(const room of Object.keys(next.rooms)){const defaults=['lamp','sculpture','lighting','panel',...(['living','master','second'].includes(room)?['textile','curtain']:[]),...(room==='living'?['art-tv','presence','audio']:[]),...(room==='dining'?['artwork']:[]),...(room==='bath'?['mirror','presence']:[]),...(room==='kitchen'?['coffee','climate']:[]),...(room==='utility'?['laundry','cleaning']:[])];next.rooms[room]=LIFE_ITEMS.filter(i=>i.rooms.includes(room)&&defaults.includes(i.id)).map(i=>i.id);}return next;}
export function lifestyleRows(value){const next=normalizeLifestyle(value);return Object.entries(next.rooms).map(([room,ids])=>({room,name:LIFE_ROOM_NAMES[room],items:LIFE_ITEMS.filter(i=>ids.includes(i.id))}));}
export function sceneActions(value){const v=normalizeLifestyle(value),scene=LIFE_SCENES.find(s=>s.id===v.scene),out=[];for(const row of lifestyleRows(v)){const ids=row.items.map(i=>i.id);if(ids.includes('lighting'))out.push({room:row.name,device:'照明',value:scene.id==='night'?(ids.includes('presence')?'感应低位灯 · 8%':'手动低位灯 · 8%'):scene.light+'%'});if(ids.includes('curtain'))out.push({room:row.name,device:'窗帘',value:'开合 '+scene.curtain+'%'});if(ids.includes('art-tv'))out.push({room:row.name,device:'艺术电视',value:scene.id==='cinema'?'观影模式':scene.id==='away'||scene.id==='night'?'关闭':'艺术展示'});if(ids.includes('audio'))out.push({room:row.name,device:'背景音',value:scene.id==='home'?'轻声播放':scene.id==='cinema'?'随影片播放':'关闭'});if(ids.includes('climate'))out.push({room:row.name,device:'空气系统',value:scene.id==='away'?'保留基础策略':'按监测值联动'});}return out;}
export function lifestyleSummaryHTML(value,escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))){const v=normalizeLifestyle(value),c=COLLECTIONS.find(c=>c.id===v.collection);return '<h3>'+escape(c.name)+' · 软装与智慧生活</h3><p>新增陈设为三维概念摆位；原写实图与 VR 尚未重绘。智能场景为模拟，未连接真实设备。</p>'+lifestyleRows(v).filter(r=>r.items.length).map(r=>'<section><h4>'+escape(r.name)+'</h4><ul>'+r.items.map(i=>'<li><strong>'+escape(i.name)+'</strong> · '+escape(i.position)+'<br>'+escape(i.prepare)+'</li>').join('')+'</ul></section>').join('')+'<h4>已选场景：'+escape(LIFE_SCENES.find(s=>s.id===v.scene).name)+'</h4><ul>'+sceneActions(v).map(a=>'<li>'+escape(a.room+' · '+a.device+'：'+a.value)+'</li>').join('')+'</ul>';}
