import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildWholeGeometry,disposeWholeGeometry} from './whole-model-geometry.mjs';
import {buildDetailedHome} from './whole-model-detailed.mjs';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {MODEL_ROOMS} from './whole-model-state.mjs';

export async function createWholeModel({stage,canvas,labels,status,onSelect}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'low-power'});
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.35));renderer.setClearColor('#e6e0d5');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.05,100),controls=new OrbitControls(camera,canvas);controls.target.set(5.2,.2,3.6);controls.enableDamping=true;controls.dampingFactor=.14;controls.rotateSpeed=.65;controls.minDistance=2.5;controls.maxDistance=32;controls.maxPolarAngle=Math.PI*.475;controls.minPolarAngle=.04;controls.screenSpacePanning=true;
 const generator=new THREE.PMREMGenerator(renderer),environment=new RoomEnvironment(),env=generator.fromScene(environment,.06);scene.environment=env.texture;scene.environmentIntensity=.65;generator.dispose();environment.dispose();
 const hemi=new THREE.HemisphereLight('#fff4df','#766858',2);scene.add(hemi);const sun=new THREE.DirectionalLight('#ffebcb',3.0);sun.position.set(3,10,-5);sun.target.position.set(5,0,4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:1,far:28});sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;scene.add(sun,sun.target);const fill=new THREE.DirectionalLight('#e8eeff',.7);fill.position.set(10,6,12);scene.add(fill);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.ShadowMaterial({opacity:.17}));ground.rotation.x=-Math.PI/2;ground.position.y=-.07;ground.receiveShadow=true;scene.add(ground);
 let model=null,selected='living',visible=false,intersecting=true,raf=0,ticks=0,pointer=null,disposed=false,lastSnapshot=null,contextLost=false,quality='detailed',dragging=false,rendering=false,activeView='all';
 const composer=new EffectComposer(renderer),ao=new SSAOPass(scene,camera,512,512,12),output=new OutputPass();ao.kernelRadius=.18;ao.minDistance=.001;ao.maxDistance=.14;composer.addPass(ao);composer.addPass(output);
 function render(){raf=0;if(!visible||!intersecting||document.hidden||disposed||contextLost)return;rendering=true;controls.update();if(quality==='detailed'&&!dragging&&ticks<=0)composer.render();else renderer.render(scene,camera);placeLabels();rendering=false;if(ticks-->0)raf=requestAnimationFrame(render);}
 function invalidate(count=2){ticks=Math.max(ticks,count);if(!rendering&&!raf&&visible&&intersecting&&!disposed&&!document.hidden)raf=requestAnimationFrame(render);}
 controls.addEventListener('change',()=>invalidate(1));controls.addEventListener('start',()=>{dragging=true;invalidate();});controls.addEventListener('end',()=>{dragging=false;invalidate(18);});
 const roomLabels=MODEL_ROOMS.map(room=>{const b=document.createElement('button');b.type='button';b.textContent=room.name;b.setAttribute('aria-label','查看'+room.name+'的已选写实效果');b.addEventListener('click',()=>{select(room.id);onSelect(room.id);});labels.append(b);return {room,element:b};});
 function placeLabels(){for(const {room,element} of roomLabels){const v=new THREE.Vector3(room.center[0],.13,room.center[1]).project(camera);element.style.left=(v.x*.5+.5)*100+'%';element.style.top=(-v.y*.5+.5)*100+'%';element.hidden=v.z>1||v.z< -1||Math.abs(v.x)>.96||Math.abs(v.y)>.94||(!['all','top'].includes(activeView)&&room.id!==activeView);}}
 const highlight=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#bd9865',transparent:true,opacity:.9}));scene.add(highlight);
 function select(id){if(!MODEL_ROOMS.some(r=>r.id===id))return;selected=id;const room=MODEL_ROOMS.find(r=>r.id===id);highlight.geometry.dispose();highlight.geometry=new THREE.BufferGeometry().setFromPoints(room.p.map(([x,z])=>new THREE.Vector3(x,.032,z)));for(const r of roomLabels)r.element.setAttribute('aria-pressed',String(r.room.id===id));invalidate();}
 function view(id='all'){activeView=id;const aspect=stage.clientWidth/Math.max(stage.clientHeight,1),fit=Math.max(1,1.30/aspect);if(id==='all'){controls.target.set(5.2,.25,3.55);camera.position.set(13.0,11.5,15.2);camera.position.sub(controls.target).multiplyScalar(fit).add(controls.target);}else if(id==='top'){controls.target.set(5.2,0,3.55);camera.position.set(5.2,19*fit,3.57);}else{const r=MODEL_ROOMS.find(r=>r.id===id)||MODEL_ROOMS[0];controls.target.set(r.center[0],.5,r.center[1]);camera.position.set(r.center[0]+2.8,.5+3.5,r.center[1]+4.3);}controls.update();invalidate(16);}
 function resize(){const w=Math.max(1,stage.clientWidth),h=Math.max(1,stage.clientHeight);renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();}
 const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);const visibilityObserver=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>{intersecting=entries.some(e=>e.isIntersecting);if(intersecting)invalidate();else if(raf){cancelAnimationFrame(raf);raf=0;}},{rootMargin:'120px'}):null;visibilityObserver?.observe(stage);
 const onVisibility=()=>{if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0;}else invalidate();};document.addEventListener('visibilitychange',onVisibility);
 canvas.addEventListener('pointerdown',e=>{pointer=[e.clientX,e.clientY];});canvas.addEventListener('pointerup',e=>{if(!model||!pointer||Math.hypot(e.clientX-pointer[0],e.clientY-pointer[1])>5)return;pointer=null;const rect=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);const hit=ray.intersectObject(model,true).find(h=>{for(let n=h.object;n;n=n.parent)if(!n.visible)return false;return true;});if(!hit)return;let node=hit.object;while(node&&!node.userData.room)node=node.parent;if(node){select(node.userData.room);onSelect(node.userData.room);}});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;if(raf)cancelAnimationFrame(raf);raf=0;status.textContent='三维显示暂时中断。房间选择已保留，可继续看写实图；刷新后可以重新加载。';});canvas.addEventListener('webglcontextrestored',()=>{contextLost=false;if(lastSnapshot)update(lastSnapshot);});
 const textures={},loader=new THREE.TextureLoader(),base='/tour/catalog-assets/materials/',sources={wood:'/assets/textures/wood.jpg',linen:'/assets/textures/linen.jpg',stone:'/assets/textures/stone.jpg',oak:base+'wooden_floor_02/wooden_floor_02_diff_1k.jpg',oakNormal:base+'wooden_floor_02/wooden_floor_02_nor_gl_1k.jpg',oakArm:base+'wooden_floor_02/wooden_floor_02_arm_1k.jpg',wool:base+'poly_wool_herringbone/poly_wool_herringbone_diff_1k.jpg',woolNormal:base+'poly_wool_herringbone/poly_wool_herringbone_nor_gl_1k.jpg',marble:base+'marble_01/marble_01_diff_1k.jpg',marbleNormal:base+'marble_01/marble_01_nor_gl_1k.jpg'};
 const outcomes=await Promise.allSettled(Object.entries(sources).map(async([id,path])=>{const t=await loader.loadAsync(path);if(disposed){t.dispose();return;}t.colorSpace=/Normal|Arm/.test(id)?THREE.NoColorSpace:THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;const repeat=id==='linen'?5:id.startsWith('wool')?4:.6;t.repeat.set(repeat,repeat);t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());textures[id]=t;}));
 const textureFailed=outcomes.some(o=>o.status==='rejected');
 function update(snapshot){lastSnapshot=snapshot;if(model){scene.remove(model);disposeWholeGeometry(model);}model=(quality==='detailed'?buildDetailedHome:buildWholeGeometry)(snapshot,textures);scene.add(model);const light=model.userData.spec.light,night=light.startsWith('night'),cool=light==='daycool'||light==='nightneutral';sun.intensity=night?.35:2.55;sun.color.set(cool?'#eff3ff':'#ffefd7');hemi.intensity=night?.7:1.05;fill.intensity=night?.25:.50;renderer.toneMappingExposure=night?1.10:1.04;scene.environmentIntensity=night?.5:.8;renderer.shadowMap.needsUpdate=true;select(selected);invalidate();status.textContent=textureFailed?'部分纹理未载入，当前保留基础材质；写实图仍可查看。':(quality==='detailed'?'细节模型 · 静止时补充接触阴影':'轻量模型')+' · 拖动旋转 · 点房间查看写实图';}
 resize();view('all');
 return {update,select,view,setQuality(value){const next=value==='light'?'light':'detailed';if(quality===next)return;quality=next;if(lastSnapshot)update(lastSnapshot);},setVisible(value){visible=value;if(value){resize();invalidate(2);}else if(raf){cancelAnimationFrame(raf);raf=0;}},dispose(){disposed=true;visible=false;if(raf)cancelAnimationFrame(raf);resizeObserver.disconnect();visibilityObserver?.disconnect();document.removeEventListener('visibilitychange',onVisibility);controls.dispose();disposeWholeGeometry(model);Object.values(textures).forEach(t=>t.dispose());ao.dispose();output.dispose();composer.dispose();env.dispose();ground.geometry.dispose();ground.material.dispose();highlight.geometry.dispose();highlight.material.dispose();renderer.dispose();labels.replaceChildren();}};
}
