// Export a self-contained effect book. Product candidates are never labelled as applied scene objects.
export async function exportEffectBook(snapshot,name){
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const assets=new Map();for(const f of snapshot.frames)if(!assets.has(f.path)){const response=await fetch(f.path);if(!response.ok)throw new Error('图片未载入');const blob=await response.blob();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});assets.set(f.path,data);}
 const cards=snapshot.frames.map(f=>`<article><h2>${escape(f.name)}</h2><p>${escape(f.shared?'与客厅共用已选视角':f.changed?f.label:'沿用风格原方案')}</p><img src="${assets.get(f.path)}" alt="${escape(f.name)}"><dl>${f.items.map(([k,v])=>`<div><dt>${escape(k)}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl></article>`).join('');
 const products=snapshot.products.map(p=>`<li><a href="${escape(p.url)}" target="_blank" rel="noopener noreferrer">${escape(p.brand+' · '+p.product)}</a><p>${escape(typeof p.dimensions==='string'?p.dimensions:p.dimensions?.text||'型号、饰面与尺寸需确认')}</p></li>`).join('');
 const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>庭间 · ${escape(name)}全屋效果册</title><style>body{margin:0;background:#f4efe5;color:#463b30;font:15px/1.8 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:48px 28px}h1,h2{font-family:Georgia,'Songti SC',serif;font-weight:400}h1{font-size:36px}header{border-bottom:1px solid #cdbfae;padding-bottom:25px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:36px}img{width:100%;height:auto;display:block}article{break-inside:avoid}h2{margin-bottom:4px}p,dd{color:#81715c}dl div{display:flex;gap:16px}dd{margin:0}a{color:inherit}.note{padding:18px;border:1px solid #d9cdbb}footer{margin-top:40px;border-top:1px solid #d9cdbb}@media(max-width:700px){.grid{grid-template-columns:1fr}}@media print{body{background:white}main{padding:0}.grid{display:block}article{page-break-after:always}}</style><main><header><span>庭间 / 住进木与光</span><h1>${escape(name)} · 全屋效果册</h1><p>按你的方案选择汇总 · ${escape(snapshot.createdAt.slice(0,10))}</p></header><p class="note">独立视角的写实概念效果汇总，非实拍、非施工图。已完成的单品搭配按所选画面保留；未调整空间沿用风格原方案。客餐厅共用所选视角，跨房间材质收口与光线还需统一深化。本册不代表任意购买候选已完成整屋重渲染。</p><div class="grid">${cards}</div><footer><h2>购买候选 · 尚未替换进画面</h2><p>用于试坐、看样与询价，并非图中精确商品。型号、尺寸、颜色、价格和交付条件需向品牌确认。</p><ul>${products||'<li>尚未加入候选</li>'}</ul><p>大面玻璃与外窗为视觉设想，需结合原始结构、物业条件、玻璃与防护专项深化；生活阳台保留开启通风。</p></footer></main></html>`;
 const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='庭间-'+name+'-全屋效果册.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
