import fs from 'node:fs/promises';import assert from 'node:assert/strict';import path from 'node:path';
import {fresh,validState,updateItem,assess,footprint,collides,inside} from '../src/state.mjs';
const catalog=JSON.parse(await fs.readFile('dist/assets/models/catalog.json','utf8'));const state=fresh(),results=[];
assert.equal(catalog.length,4);for(const m of catalog){assert.equal(assess(m.id,state,catalog).length,0,m.id+' default layout conflict');const bytes=await fs.readFile('dist/assets/models/'+m.file);assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(8),bytes.length);const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)));assert(json.meshes.length>0);assert(json.images?.length>0);assert(json.materials.every(m=>m.pbrMetallicRoughness.baseColorTexture));assert(bytes.length<25*1024*1024);}
results.push('Four supplied textured GLBs valid, below hosting size limit; default furniture footprints do not overlap');
const twice=updateItem(state,'sofa',{scale:1.5});assert(Math.abs(catalog[0].width*twice.items.sofa.scale-3.15)<1e-9);assert.equal(state.items.sofa.scale,1);assert.throws(()=>updateItem(state,'sofa',{scale:0}));assert.throws(()=>updateItem(state,'chair',{x:Infinity}));assert.throws(()=>updateItem(state,'chair',{scale:3}));assert.throws(()=>validState({}));assert.throws(()=>validState({...state,floor:'unknown'}));
const outside=updateItem(state,'sofa',{x:6});assert(assess('sofa',outside,catalog).some(x=>x.includes('超出')));const overlap=updateItem(state,'table',{x:state.items.sofa.x,z:state.items.sofa.z});assert(assess('sofa',overlap,catalog).some(x=>x.includes('重叠')));const hidden=updateItem(overlap,'table',{visible:false});assert(!assess('sofa',hidden,catalog).length);assert.deepEqual(validState(JSON.parse(JSON.stringify(twice))),twice);assert.equal(updateItem(state,'table',{rotation:-15}).items.table.rotation,345);results.push('Reference-unit scaling, rotation, no-mutation edits, bounds/overlap warnings, invalid inputs and save/import round-trip');
const html=await fs.readFile('dist/lab/index.html','utf8'),js=await fs.readFile('src/app.mjs','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);for(const x of js.matchAll(/\$\('#([a-z-]+)'\)/g))assert(ids.includes(x[1]),x[1]+' missing');for(const asset of ['/app.js','/app.css','/tour/index.html'])await fs.access('dist'+asset);assert.equal((html.match(/data-view=/g)||[]).length,3);assert(js.includes('document.modelContext'));results.push('Main DOM hooks, routes, view modes and feature-detected WebMCP registration present');
const tour=await fs.readFile('dist/tour/index.html','utf8');const home=await fs.readFile('dist/index.html','utf8');assert.equal(home,tour);assert(home.includes('data-legacy-frame'));assert(home.includes('data-lab-frame'));assert(home.includes('data-music-track'));assert(!home.includes('data-mode="vr"'));await fs.access('dist/tour/legacy.html');await fs.access('dist/lab/index.html');results.push('Current design, music player and retained furniture lab routes present; historical VR removed');
async function all(dir){let files=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())files.push(...await all(p));else files.push(p);}return files;}let total=0;for(const p of await all('dist')){const size=(await fs.stat(p)).size;assert(size<25*1024*1024,p+' too large');total+=size;}results.push('All public assets below 25 MiB; total '+(total/1024/1024).toFixed(1)+' MiB');
await fs.mkdir('verification',{recursive:true});await fs.writeFile('verification/checks.json',JSON.stringify({passed:true,browserUITested:false,webMCPRuntimeValidated:false,limitation:'Managed preview not available for plain static sites. No browser automation was used. Asset and application-state checks performed. No browser timing measurements were made in this update.',results},null,2));console.log(JSON.stringify({passed:true,results}));
