import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
// v19 removes old historical VR; all current panoramas now fit on the Site itself.
await fs.rm('build',{recursive:true,force:true});
await fs.cp('dist','build',{recursive:true,filter:p=>!p.includes('.openai')&&!p.includes('scene-edits-v25')&&!p.includes('designs-v26')&&!p.includes('designer-v34')&&!p.includes('final-v35')&&!p.includes('designs-v36')});
const media=JSON.parse(await fs.readFile('verification/v25/media-origin.json','utf8'));
await fs.writeFile('build/scene-edit-origin.json',JSON.stringify(media));
const {origin:sourceOrigin}=JSON.parse(await fs.readFile('verification/v26/media-origin.json','utf8'));
const origin=sourceOrigin.replace(/https:\/\/raw\.githubusercontent\.com\/17621441006\/tingjian-studio\/([a-f0-9]{40})\/dist/, 'https://cdn.jsdelivr.net/gh/17621441006/tingjian-studio@$1/dist');
const {origin:v34Source}=JSON.parse(await fs.readFile('verification/v34/media-origin.json','utf8'));
const v34Origin=v34Source.replace('https://raw.githubusercontent.com/17621441006/tingjian-studio/', 'https://cdn.jsdelivr.net/gh/17621441006/tingjian-studio@');
const {origin:v35Source}=JSON.parse(await fs.readFile('verification/v35/media-origin.json','utf8'));
const v35Origin=v35Source.replace('https://raw.githubusercontent.com/17621441006/tingjian-studio/', 'https://cdn.jsdelivr.net/gh/17621441006/tingjian-studio@');
const {origin:v36Source}=JSON.parse(await fs.readFile('verification/v36/media-origin.json','utf8'));
const v36Origin=v36Source.replace('https://raw.githubusercontent.com/17621441006/tingjian-studio/', 'https://cdn.jsdelivr.net/gh/17621441006/tingjian-studio@');
const html=await fs.readFile('build/tour/legacy.html','utf8');
await fs.writeFile('build/tour/legacy.html',html.replace('</head>', '<script>globalThis.__TINGJIAN_V26_ORIGIN__='+JSON.stringify(origin).replaceAll('<','\\u003c')+';globalThis.__TINGJIAN_V34_ORIGIN__='+JSON.stringify(v34Origin).replaceAll('<','\\u003c')+';globalThis.__TINGJIAN_V35_ORIGIN__='+JSON.stringify(v35Origin).replaceAll('<','\\u003c')+';globalThis.__TINGJIAN_V36_ORIGIN__='+JSON.stringify(v36Origin).replaceAll('<','\\u003c')+';</script></head>'));
let bytes=0,count=0;async function walk(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())await walk(p);else{bytes+=(await fs.stat(p)).size;count++;}}}await walk('build');
assert(bytes<256*1024*1024-100000,'deployment exceeds platform budget');
console.log({hostingBytes:bytes,files:count,panoramas:'same-origin'});
