import {createScene} from './scene.mjs';
import {DEFAULTS,fresh,validState,updateItem,assess,ROOM} from './state.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='tingjian-living-v1';let state=fresh(),selected='sofa',catalog=[],engine=null,history=[],view='room',tool='look',toastTimer,dragBefore=null;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3800);}
try{const saved=localStorage.getItem(KEY);if(saved)state=validState(JSON.parse(saved));}catch{toast('上次方案无法读取，已恢复默认摆放。');}
function checkpoint(){history.push(structuredClone(state));if(history.length>35)history.shift();$('#undo').disabled=false;}
function apply(next,{record=true}={}){const valid=validState(next);if(record)checkpoint();state=valid;updateUI();engine?.sync(state,selected);}
function patchItem(id,patch,{record=true}={}){apply(updateItem(state,id,patch),{record});}
function select(id){if(!catalog.some(x=>x.id===id))throw Error('这件家具不存在');selected=id;updateUI();engine?.sync(state,selected);}
function updateUI(){const m=catalog.find(c=>c.id===selected);if(!m)return;const i=state.items[selected],cm=x=>Math.round(x*i.scale*100);$('#item-name').textContent=m.name;$('#item-index').textContent=String(catalog.indexOf(m)+1).padStart(2,'0');$('#size-status').textContent=i.verified?'宽度已由你核对 · 深高待复核':'方案尺寸 · 待实物校准';$('#size-status').classList.toggle('verified',i.verified);$('#dimensions-readout').innerHTML=[['宽 / cm',m.width],['深 / cm',m.depth],['高 / cm',m.height]].map(([label,v])=>`<div><span>${label}</span><strong>${cm(v)}</strong></div>`).join('');$('#width').value=cm(m.width);$('#width').min=Math.ceil(m.width*.35*100);$('#width').max=Math.floor(m.width*2.2*100);$('#verified').checked=i.verified;$('#rotation').value=Math.round(i.rotation/5)*5;$('#rotation-output').textContent=Math.round(i.rotation)+'°';$('#position-x').value=Math.round(i.x*100);$('#position-z').value=Math.round(i.z*100);$('#toggle-item').textContent=i.visible?'暂时移出':'放回空间';$('#show-dimensions').checked=state.showDimensions;for(const b of $$('[data-item]')){b.setAttribute('aria-pressed',b.dataset.item===selected);b.classList.toggle('is-hidden',!state.items[b.dataset.item].visible);}for(const b of $$('[data-floor]'))b.setAttribute('aria-pressed',b.dataset.floor===state.floor);
 const warnings=assess(selected,state,catalog);$('#placement-note').classList.toggle('warning',warnings.length>0);$('#placement-note').textContent=!i.visible?'已移出画面，仍保留尺寸和位置。':warnings.length?'△ '+warnings.join('；'):'✓ 在客餐厅范围内，未与其他试摆家具重叠。';$('#undo').disabled=!history.length;
}
function syncView(next){view=next;for(const b of $$('[data-view]'))b.setAttribute('aria-pressed',b.dataset.view===next);for(const b of $$('[data-station]'))b.setAttribute('aria-pressed',b.dataset.station===(engine?.getStation()||'entry'));$('#interaction-hint').textContent=tool==='move'?'拖动家具摆放 · 旋转和尺寸在右侧':next==='room'?'拖动画面环视 · 点击家具选中':'拖动旋转 · 滚轮远近 · 点击家具选中';}
function setView(next,station='entry'){if(!['room','orbit','top'].includes(next))throw Error('未知视角');if(!['entry','living','balcony'].includes(station))throw Error('未知站位');engine?.setView(next,station);if(next==='room'&&tool==='move')setTool('look');syncView(next);}
function setTool(next){tool=next;engine?.setTool(next);for(const b of $$('[data-tool]'))b.setAttribute('aria-pressed',b.dataset.tool===next);syncView(engine?.getView()||view);engine?.sync(state,selected);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));toast('已保存到当前浏览器。也可以导出方案备份。');return {saved:true,storage:'this-browser'};}catch{toast('浏览器未允许保存，请使用“导出方案”。');throw Error('当前浏览器无法保存');}}
function guarded(fn){return (...args)=>{try{return fn(...args);}catch(e){toast(e.message||'这次操作没有完成');updateUI();}};}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#transform-form').addEventListener('submit',e=>e.preventDefault());$('#width').addEventListener('change',guarded(()=>{const m=catalog.find(x=>x.id===selected);patchItem(selected,{scale:Number($('#width').value)/100/m.width,verified:false});}));$('#verified').addEventListener('change',guarded(()=>patchItem(selected,{verified:$('#verified').checked})));let rotating=false;$('#rotation').addEventListener('pointerdown',()=>{checkpoint();rotating=true;});$('#rotation').addEventListener('input',guarded(()=>patchItem(selected,{rotation:Number($('#rotation').value)},{record:!rotating})));$('#rotation').addEventListener('change',()=>{rotating=false;});$('#rotation').addEventListener('pointercancel',()=>{rotating=false;});for(const [id,amount]of [['#rotate-minus',-15],['#rotate-plus',15]])$(id).addEventListener('click',guarded(()=>patchItem(selected,{rotation:state.items[selected].rotation+amount})));
for(const [id,k]of [['#position-x','x'],['#position-z','z']])$(id).addEventListener('change',guarded(()=>patchItem(selected,{[k]:Number($(id).value)/100})));
$('#toggle-item').addEventListener('click',guarded(()=>patchItem(selected,{visible:!state.items[selected].visible})));$('#reset-item').addEventListener('click',guarded(()=>patchItem(selected,DEFAULTS[selected])));$('#show-dimensions').addEventListener('change',()=>apply({...state,showDimensions:$('#show-dimensions').checked}));for(const b of $$('[data-floor]'))b.addEventListener('click',()=>apply({...state,floor:b.dataset.floor}));for(const b of $$('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view));for(const b of $$('[data-tool]'))b.addEventListener('click',()=>setTool(b.dataset.tool));for(const b of $$('[data-station]'))b.addEventListener('click',()=>{setView('room',b.dataset.station);});$('#reset-view').addEventListener('click',()=>setView(view));$('#save').addEventListener('click',guarded(save));$('#undo').addEventListener('click',()=>{if(history.length)apply(history.pop(),{record:false});});
$('#export').addEventListener('click',()=>download('tingjian-living-plan.json',JSON.stringify({...state,room:{polygon:ROOM.polygon,height:ROOM.height,measured:false},dimensions:catalog.map(m=>({id:m.id,name:m.name,widthCm:Math.round(m.width*state.items[m.id].scale*100),depthCm:Math.round(m.depth*state.items[m.id].scale*100),heightCm:Math.round(m.height*state.items[m.id].scale*100),widthVerifiedByUser:state.items[m.id].verified})),note:'参考摆放方案，非施工图。房间与深高尺寸未实测。'},null,2)));
$('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('方案文件过大');const input=validState(JSON.parse(await file.text()));apply(input);toast('已载入方案，可继续调整。');}catch(err){toast('无法导入：'+err.message);}e.target.value='';});$('#retry').addEventListener('click',()=>location.reload());$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen();}catch{toast('此浏览器不支持全屏，可用浏览器放大查看。');}});
$('#viewport').addEventListener('keydown',guarded(e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName))return;if(e.key.toLowerCase()==='r'){e.preventDefault();patchItem(selected,{rotation:state.items[selected].rotation+15});}const directions={ArrowLeft:[-.05,0],ArrowRight:[.05,0],ArrowUp:[0,-.05],ArrowDown:[0,.05]};if(directions[e.key]&&tool==='move'){e.preventDefault();const [x,z]=directions[e.key];patchItem(selected,{x:state.items[selected].x+x,z:state.items[selected].z+z});}}));
function stateSnapshot(){return {selected,view,tool,floor:state.floor,roomMeasured:false,items:catalog.map(m=>{const i=state.items[m.id];return {id:m.id,name:m.name,...i,widthCm:Math.round(m.width*i.scale*100),depthCm:Math.round(m.depth*i.scale*100),heightCm:Math.round(m.height*i.scale*100),warnings:assess(m.id,state,catalog)};})};}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const defs=[{name:'get_room_configuration',title:'读取客厅方案',description:'读取当前家具、方案尺寸、位置和重叠提示。房间未实测。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>stateSnapshot()},{name:'configure_furniture',title:'调整家具',description:'选择一件上传家具，设置位置（米）、旋转（度）、等比尺寸或显示状态，并更新可见画面。',inputSchema:{type:'object',properties:{id:{type:'string',enum:Object.keys(DEFAULTS)},x:{type:'number',minimum:-8,maximum:8},z:{type:'number',minimum:-8,maximum:8},rotation:{type:'number'},widthCm:{type:'number',exclusiveMinimum:0},visible:{type:'boolean'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!catalog.some(m=>m.id===input.id)||Object.keys(input).some(k=>!['id','x','z','rotation','widthCm','visible'].includes(k)))throw Error('家具参数无效');const patch={};for(const key of ['x','z','rotation','visible'])if(key in input)patch[key]=input[key];if('visible'in patch&&typeof patch.visible!=='boolean')throw Error('visible 必须是布尔值');if('widthCm'in input){if(!Number.isFinite(input.widthCm)||input.widthCm<=0)throw Error('宽度无效');patch.scale=input.widthCm/100/catalog.find(m=>m.id===input.id).width;patch.verified=false;}const next=updateItem(state,input.id,patch);select(input.id);apply(next);await new Promise(resolve=>requestAnimationFrame(resolve));return stateSnapshot();}},{name:'navigate_room_view',title:'改变客厅视角',description:'在客厅内选择人在屋内、环绕或俯视视角，可指定玄关、客厅或阳台站位。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['room','orbit','top']},station:{type:'string',enum:['entry','living','balcony']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||Object.keys(input).some(k=>!['view','station'].includes(k)))throw Error('视角参数无效');setView(input.view,input.station||'entry');await new Promise(resolve=>setTimeout(resolve,700));return {view,station:engine.getStation()};}}];for(const d of defs){try{Promise.resolve(context.registerTool({...d,annotations:{...d.annotations,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
(async()=>{try{const res=await fetch('/assets/models/catalog.json');if(!res.ok)throw Error('家具目录读取失败');catalog=await res.json();for(const [index,m]of catalog.entries()){const b=document.createElement('button');b.className='catalog-card';b.dataset.item=m.id;b.innerHTML=`<img src="/assets/models/${m.id}.jpg" alt=""><span><strong>${m.name}</strong><small>模型 ${String(index+1).padStart(2,'0')} · 已导入</small></span>`;b.addEventListener('click',()=>select(m.id));$('#catalog-list').append(b);}updateUI();engine=await createScene({viewport:$('#viewport'),canvas:$('#scene'),catalog,getState:()=>state,onSelect:select,onProgress:text=>$('#load-progress').textContent=text,onDragStart:()=>{checkpoint();dragBefore=structuredClone(state);},onDragEnd:()=>{dragBefore=null;},onMove:(id,x,z)=>patchItem(id,{x:Math.round(x*100)/100,z:Math.round(z*100)/100},{record:false})});engine.sync(state,selected);$('#loading').hidden=true;registerTools();}catch(error){$('#loading').hidden=true;$('#load-error').hidden=false;$('#error-message').textContent=error.message?.includes('WebGL')?'当前浏览器没有启用 WebGL。请用最新版 Chrome、Edge 或 Safari 打开。':'家具资源尚未全部载入，请检查网络后重试。';console.error(error);}})();
