export const ROOM = {name:'客餐厅',height:2.65,polygon:[[-1.825,-2.47],[1.825,-2.47],[1.825,2.47],[-3.455,2.47],[-3.455,.60],[-1.825,.60]],balcony:[[-1.825,-4.06],[.775,-4.06],[.775,-3.46],[1.825,-3.46],[1.825,-2.47],[-1.825,-2.47]]};
export const DEFAULTS={sofa:{x:-1.18,z:-.65,rotation:90,scale:1,visible:true,verified:false},table:{x:.38,z:-.65,rotation:90,scale:1,visible:true,verified:false},lounge:{x:.85,z:1.10,rotation:190,scale:1,visible:true,verified:false},chair:{x:-2.68,z:1.73,rotation:65,scale:1,visible:true,verified:false}};
export const fresh=()=>({version:1,items:structuredClone(DEFAULTS),floor:'stone',showDimensions:true});
export function inside(x,z,p=ROOM.polygon){let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a[1]>z)!==(b[1]>z))&&(x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0]))c=!c;}return c;}
export function footprint(item,meta){const a=item.rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a),w=meta.width*item.scale/2,d=meta.depth*item.scale/2;return [[-w,-d],[w,-d],[w,d],[-w,d]].map(([x,z])=>[item.x+x*c+z*s,item.z-x*s+z*c]);}
export function collides(a,b){for(const p of [a,b])for(let i=0;i<4;i++){const n=[-(p[(i+1)%4][1]-p[i][1]),p[(i+1)%4][0]-p[i][0]],project=q=>q.map(v=>v[0]*n[0]+v[1]*n[1]),u=project(a),v=project(b);if(Math.max(...u)<=Math.min(...v)+.002||Math.max(...v)<=Math.min(...u)+.002)return false;}return true;}
export function assess(id,state,catalog){const item=state.items[id],meta=catalog.find(x=>x.id===id);if(!item?.visible||!meta)return [];const p=footprint(item,meta),messages=[];const samples=[...p,...p.map((a,i)=>[(a[0]+p[(i+1)%4][0])/2,(a[1]+p[(i+1)%4][1])/2])];if(samples.some(([x,z])=>!inside(x,z)))messages.push('家具轮廓超出客餐厅范围');for(const other of catalog)if(other.id!==id&&state.items[other.id]?.visible&&collides(p,footprint(state.items[other.id],other)))messages.push('与'+other.name+'的包围轮廓重叠');return messages;}
export function validState(input){if(!input||input.version!==1||!input.items)throw Error('方案格式不兼容');const out=fresh();for(const id of Object.keys(DEFAULTS)){const i=input.items[id];if(!i)throw Error('缺少家具');for(const k of ['visible','verified'])if(k in i&&typeof i[k]!=='boolean')throw Error('显示状态格式错误');for(const k of ['x','z','rotation','scale'])if(!Number.isFinite(i[k]))throw Error('尺寸或位置不是有效数值');if(Math.abs(i.x)>8||Math.abs(i.z)>8||i.scale<.35||i.scale>2.2)throw Error('尺寸或位置超出允许范围');out.items[id]={x:i.x,z:i.z,rotation:((i.rotation%360)+360)%360,scale:i.scale,visible:i.visible!==false,verified:i.verified===true};}if(!['stone','wood'].includes(input.floor))throw Error('不支持的地面材质');out.floor=input.floor;if('showDimensions'in input&&typeof input.showDimensions!=='boolean')throw Error('尺寸显示设置无效');out.showDimensions=input.showDimensions!==false;return out;}
export function updateItem(state,id,patch){if(!DEFAULTS[id])throw Error('未知家具');const allowed=['x','z','rotation','scale','visible','verified'];if(Object.keys(patch).some(k=>!allowed.includes(k)))throw Error('不支持的参数');return validState({...state,items:{...state.items,[id]:{...state.items[id],...patch}}});}
